# Generated by Django 3.2.15 on 2022-08-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_to_do', models.CharField(max_length=20)),
                ('by_when_to_do', models.DateTimeField()),
            ],
        ),
    ]
